import Nav from "../../components/Nav/Nav";
import { useState, useEffect } from "react";
import Card from "../../components/Card/Card";
import styles from "../../styles/Home.module.css";
import DefaultLayout from "../../components/layout/Default";
import Head  from "next/head";

function Home() {
    const [cats, setCats] = useState([]);

    const fetchCats = async () => {
      const response = await fetch("/api/cats");
      const data = await response.json();
  
      setCats(data);
    };
  
    useEffect(() => {
      fetchCats();
    }, []);
  

    return ( 
        <div className={styles.container}>
        <Head>
          <title>Our Cats</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
       <DefaultLayout>
        <div className="container mt-5">
            <div style={{
                display: 'flex', 
                flexWrap: 'wrap', 
                
                }}>
                {cats.map((cat) => (
                    <Card
                    key={cat.id}
                        name={cat.name}
                        id={cat.id}
                        phone={cat.phone}
                        email={cat.email}
                        image={{ url: cat.image.url, alt: cat.image.alt }}
                        isFavourite={cat.favoured}
                    
                    />
                    ))}

            </div>
        </div>
       </DefaultLayout>
        </div>
    );
}

export default Home;